data_db:  
  image: busybox
  volumes:
    - /var/lib/postgresql
  container_name: data_db
db:
  build: ./postgis
  volumes_from: 
  - data_db
  ports:
  - "5432:5432"
  environment:
  - USERNAME=docker
  - PASS=docker
  container_name: db
adminer:
  image: clue/adminer
  ports:
  - "81:80"
  container_name: adminer
data_geoserver:  
  image: busybox
  volumes:
    - /var/lib/geoserver:/opt/geoserver/data_dir
  container_name: data_geo
geoserver:
  image: kartoza/geoserver
  volumes_from: 
  - data_geoserver
  ports:
  - "8090:8080"
  links:
  - db:db
  environment:
  - USERNAME=docker
  - PASS=docker
  container_name: geo
rest:  
  build: restapi/.
  ports:
  - "80:8080"
  - "8081:8081"
  container_name: rest
  environment: 
  - MACHINEIP=$(docker-machine ip default)
  volumes:
    - /src:/restapi
  command: node /src/index.js
h2o:  
  build: ./h2o
  ports:
  - "54321:54321"
  command: java -Xmx1g -jar /opt/h2o.jar
  container_name: h2o